
name: detect broken links within Awesome Search resources

on:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "test"
